
export const ADD_PRODUCT = "ADD_PRODUCT";
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SINGLE_PRODUCT = "SINGLE_PRODUCT";
export const SORT_BY_FIRST_LAST_UPLOAD = "SORT_BY_FIRST_LAST_UPLOAD";
export const SORT_BY_LAST_UPLOAD = "SORT_BY_LAST_UPLOAD";
export const SORT_BY_FIRST_UPLOAD = "SORT_BY_FIRST_UPLOAD";
export const SORT_BY_RESET = "SORT_BY_RESET";